# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 198fa3503a001fc1cff57e5fadf37f34b8b70dd95afb9c04a715a8db499119b6c793ffcb9acbe0747bdefdc43d22f24adc57673a2c1050684404ace5c8bb4ae0
  dev_github_api_key: 5ff0a4831d8bdb9ba52f
  dev_github_api_secret: f49c787a11073d151c2191e8e44465f5b36110c3
  dev_github_access_token: c27df3b4ccc8a710b43c51b69848247aae197192

  dev_s3_access_key_id: AKIAJHP6SKMCKZYARZ3A
  dev_s3_secret_access_key: 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

  dev_s3_bucket_name: dev-co-pro-images

test:
  secret_key_base: 3d254f5d35785be91fa4343798213c45f4b2ed2063b8592d464760604068108e303ac706d5b591f1c9081e63c54378b18b59195568dfb4d0a69c36d6da0a9b90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # github_api_key: <%= ENV["GITHUB_API_KEY"] %>
  # github_api_secret: <%= ENV["GITHUB_API_SECRET"] %>
  # github_access_token: <%= ENV["GITHUB_ACCESS_TOKEN"] %>

  # s3_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  # s3_secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>

  # s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
