# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:

test:

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # github_api_key: <%= ENV["GITHUB_API_KEY"] %>
  # github_api_secret: <%= ENV["GITHUB_API_SECRET"] %>
  # github_access_token: <%= ENV["GITHUB_ACCESS_TOKEN"] %>

  # s3_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  # s3_secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>

  # s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
